# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e4c7ec3ef098dfba965757da959cc8f"
application_url = "https://broken-installations-sad-mathematics.trycloudflare.com"
embedded = true
name = "shippywhippy"
handle = "shippywhippy"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "froggya.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_products,read_shipping,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://broken-installations-sad-mathematics.trycloudflare.com/auth/callback",
  "https://broken-installations-sad-mathematics.trycloudflare.com/auth/shopify/callback",
  "https://broken-installations-sad-mathematics.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
